services:

  frontend:
    build:
      context: ./frontend
      args:
        NEXT_PUBLIC_API_URL: http://api:8080
        NEXT_PUBLIC_NEXT_PUBLIC_API_URL: http://localhost:8080
    ports:
      - "3000:3000"
    depends_on: [ api ]
    environment:
      NEXT_PUBLIC_API_URL: http://api:8080

  api:
    build: ./backend
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      PORT: 8080
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/full-stack?sslmode=disable
      JWT_SECRET: super-secret

  postgres:
    image: postgres:17-alpine
    restart: always
    environment:
      POSTGRES_DB: full-stack
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 3s
      timeout: 3s
      retries: 10
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
