services:

  frontend:
    build:
      context: ./frontend
      args:
        NEXT_PUBLIC_API_URL: http://api:8080
    ports:
      - "3000:3000"
    depends_on: [ api ]
    environment:
      NEXT_PUBLIC_API_URL: http://api:8080

  api:
    build: ./backend
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      ALLOW_ORIGINS: "http://frontend:3000,http://localhost:3000"
      PORT: 8080
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/full-stack-test?sslmode=disable
      JWT_SECRET: super-secret

  postgres:
    image: postgres:17-alpine
    restart: always
    environment:
      POSTGRES_DB: full-stack-test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 3s
      timeout: 3s
      retries: 10
    volumes:
      - pgdata-test:/var/lib/postgresql/data

  e2e:
    build: ./e2e
    ports:
      - "9323:9323"
    depends_on:
      frontend:
        condition: service_started
    environment:
      BASE_URL: http://frontend:3000
    command: >
      sh -c "
        pnpm test;
        pnpm exec playwright show-report --host 0.0.0.0 --port 9323 playwright/reports
      "
    volumes:
      - ./e2e:/app

volumes:
  pgdata-test:
